MODEL:
  OUTPUT_PATH: "/home/che/ml-hw/hw2/weights/model.pth"
  LR: 0.001
  EPOCH: 5

DATA:
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  RESIZE: [224, 224]
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 2
  VALIDATION_SIZE: 0.2
  NUM_WORKERS: 4

PATH:
  TRAIN_SET: "/home/che/ml_hw2_image"
  TEST_SET: "/home/che/ml_hw2_image"

DEVICE:
  GPU: 1
  CUDA: False #is True before
